spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mealplanner
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: user
      password: password123

  sql:
    init:
      mode: always

server:
  port: 8080
